services:
  postgres:
    image: postgres:16-alpine
    container_name: sandwich-postgres
    environment:
      POSTGRES_DB: sandwich_delivery
      POSTGRES_USER: sandwich_user
      POSTGRES_PASSWORD: sandwich_pass123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sandwich_user -d sandwich_delivery"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: